languageCode = "en"
languageName = "English"
weight = 1

title = "Luke Charters"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false

  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[author]
  name = "Luke Charters"
  image = "img/thumbs.png"
  headline = "Sysadmin / Macadmin / Dadmin"
  # bio = "Systems Engineer who needs to finish writing this bio."
  links = [
  # { email = "mailto:hello@your_domain.com" },
  # { link = "https://link-to-some-website.com/" },
  { github = "https://github.com/lukecharters" },
  { linkedin = "https://linkedin.com/in/lukecharters" },
  { slack = "https://macadmins.slack.com/team/UDNJ1F544" },
  ]
